# Generated by Django 3.1.4 on 2020-12-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0007_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('userprofile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userProfile.profile')),
            ],
        ),
    ]
