# Generated by Django 3.1.4 on 2020-12-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20201224_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_user',
            new_name='follow_profile',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='user_profile',
        ),
    ]
