# Generated by Django 3.1.4 on 2020-12-26 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_profile_user'),
        ('follow', '0003_auto_20201226_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follow_profile', to='userProfile.profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='userProfile.profile'),
        ),
    ]
