# Generated by Django 3.1.4 on 2020-12-18 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(blank=True, max_length=255)),
                ('tweet_image', models.ImageField(upload_to='media/post/%Y/%m')),
                ('tweet_likes', models.IntegerField(default=0)),
                ('tweet_comments', models.IntegerField(default=0)),
                ('tweet_shares', models.IntegerField(default=0)),
                ('tweet_downloads', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
