# Generated by Django 3.1.4 on 2020-12-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_auto_20201221_0144'),
        ('twitter', '0004_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='post',
            name='userprofile',
            field=models.ManyToManyField(null=True, to='userProfile.UserProfile'),
        ),
    ]
