# Generated by Django 3.1.4 on 2020-12-21 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20201221_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tweet_downloads',
        ),
    ]
