# Generated by Django 3.1.4 on 2020-12-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_auto_20201221_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
