# Generated by Django 3.1.4 on 2020-12-21 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_profile_user'),
        ('twitter', '0011_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorprofile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userProfile.profile'),
        ),
    ]
