# Generated by Django 3.1.4 on 2020-12-22 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_profile_user'),
        ('twitter', '0013_auto_20201221_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userProfile.profile'),
        ),
    ]
