# Generated by Django 3.1.4 on 2020-12-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0014_auto_20201222_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='authorprofile',
        ),
    ]
