# Generated by Django 3.1.4 on 2020-12-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_auto_20201221_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
