# Generated by Django 3.1.4 on 2020-12-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_remove_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
